[package]
name = "kilo-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "3.0.0"
clap = "4.5.4"
crossbeam = "0.8.4"
crossbeam-utils = "0.8.19"
libc = "0.2.153"
signal-hook = "0.3.17"
